package aula;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Professor
 */
public class Janela extends javax.swing.JFrame {

    public static void escolha() {
        int n = Integer.parseInt(JOptionPane.showInputDialog("Digite 1 para calculadora de media\nDigite 2 para calculadora de formula de bhaskara\nDigite 3 para manipular strings\nDigite 0 para sair"));
        if (n == 1) {
            calcMedia();
        } else if (n == 2) {
            calcformuladebhaskara();
        } else if (n == 3) {
            manipulaString();
        } else if (n == 0) {
            JOptionPane.showMessageDialog(null, "Volte sempre!");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma opção valida");
            zoeiras();
        }
    }

    public static void calcMedia() {
        int qtd = Integer.parseInt(JOptionPane.showInputDialog("Digite a quantidade de numeros que deseja calcular a média."));
        float soma = 0;
        for (int i = 1; i <= qtd; i++) {
            soma = soma + Integer.parseInt(JOptionPane.showInputDialog("digite o " + i + " numero!"));
        }
        float media = soma / qtd;
        JOptionPane.showMessageDialog(null, soma);

    }

    public static void calcformuladebhaskara() {
        int a = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de a."));
        int b = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de b."));
        int c = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de c."));
        double delta = b * b - 4 * a * c;
        double x1 = (-b + Math.sqrt(delta)) / 2 * a;
        double x2 = (-b - Math.sqrt(delta)) / 2 * a;
        JOptionPane.showMessageDialog(null, "resposta: " + x1);
        JOptionPane.showMessageDialog(null, "resposta: " + x2);

    }

    public static void manipulaString() {
        int num = Integer.parseInt(JOptionPane.showInputDialog("Digite um numero inteiro"));
        String mensagem = "o numero digitado é ";
        if (num < 0) {
            mensagem += "positivo";
        } else if (num > 0) {
            mensagem += "negativo";
        } else {
            mensagem += "neutro";
        }
        if (num % 2 == 0) {
            mensagem += " e par";
        } else {
            mensagem += " e ímpar";
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public static void zoeiras() {
        String sacanagem = "oi";
        for (int i = 1; i < 2; i--) {
            sacanagem += JOptionPane.showInputDialog(sacanagem);
            if (sacanagem.contains("palmeiras não tem mundial")) {
                i = 3;
            }
        }
        JOptionPane.showMessageDialog(null, "isso mesmo!");
        escolha();

    }

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        botaoEscolha = new javax.swing.JButton();
        botaoPares = new javax.swing.JButton();
        botaoPrimos = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuTela2 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuSobreItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEscolha.setText("Aulas iniciais");
        botaoEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolhaActionPerformed(evt);
            }
        });
        painel.add(botaoEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, 40));

        botaoPares.setText("Pares");
        botaoPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoParesActionPerformed(evt);
            }
        });
        painel.add(botaoPares, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, 40));

        botaoPrimos.setText("Primos");
        botaoPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrimosActionPerformed(evt);
            }
        });
        painel.add(botaoPrimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 110, 40));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sala_de_aula.jpg"))); // NOI18N
        painel.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuArquivo.setText("Arquivo");

        menuTela2.setText("Tela 2");
        menuTela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTela2ActionPerformed(evt);
            }
        });
        menuArquivo.add(menuTela2);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        barraMenu.add(menuArquivo);

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });

        menuSobreItem.setText("Sobre este item");
        menuSobre.add(menuSobreItem);

        barraMenu.add(menuSobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolhaActionPerformed
        escolha();
    }//GEN-LAST:event_botaoEscolhaActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed

    }//GEN-LAST:event_menuSobreActionPerformed

    private void botaoParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoParesActionPerformed
        int digito = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite um número inteiro positivo!"));
        String resultado = "Os números pares de 0 até " + digito + " são:\n";
        for (int i = 0; i <= digito; i++) {
            if (i % 2 == 0) {
                resultado += "\n" + i;
            }
        }
        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_botaoParesActionPerformed

    private void botaoPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrimosActionPerformed
        int digito = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite um número inteiro positivo!"));
        String resultado = "Os números primos de 0 até " + digito + " são:\n";
        for (int i = 1; i <= digito; i++) {
            int divisores = 0;
            for (int j = 1; j <= i; j++) {
                if (i % j == 0) {
                    divisores ++;
                }
            }
            if(divisores == 2){
                resultado += "\n" + i + " é primo!";
            }
        }
        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_botaoPrimosActionPerformed

    private void menuTela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTela2ActionPerformed
        Tela2.abrir();
        dispose();
    }//GEN-LAST:event_menuTela2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    
    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoEscolha;
    private javax.swing.JButton botaoPares;
    private javax.swing.JButton botaoPrimos;
    private javax.swing.JLabel fundo;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem menuSobreItem;
    private javax.swing.JMenuItem menuTela2;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
